/**
 * Norwegian (bokmål) versions of the Academy articles, served at
 * /no/academy/:slug. Keys must match contentMap in Article.tsx - the
 * sitemap plugin lists a /no/academy URL for every key here.
 */
export const contentMapNo: Record<string, { title: string; description: string; body: string[] }> = {
  'dcf': {
    title: 'DCF-verdsettelse forklart: WACC, fri kontantstrøm og terminalverdi',
    description:
      'Den grundige guiden til diskontering av kontantstrømmer. Hvorfor beta betyr noe, hvordan du beregner kapitalkostnad, og hvorfor terminalverdien ofte misbrukes.',
    body: [
      '<h2>Filosofien bak diskontering</h2>',
      '<p>En aksje er ikke et tickersymbol på en skjerm; den er en eierandel i en ekte virksomhet. Egenverdien til en virksomhet er nåverdien av alle kontantstrømmene som kan tas ut av den i resten av levetiden. Diskontert kontantstrøm-modellen (DCF) er det matematiske uttrykket for denne sannheten.</p>',
      '<p>Multipler (P/E, EV/EBITDA) forteller deg hva markedet betaler <em>sammenlignet med konkurrentene</em>. En DCF prøver å fortelle deg hva virksomheten faktisk er <em>verdt</em> i absolutte tall.</p>',
      '<h3>Vektet gjennomsnittlig kapitalkostnad (WACC)</h3>',
      '<p>En krone i morgen er mindre verdt enn en krone i dag. WACC er diskonteringsrenten som brukes for å regne fremtidige kontantstrømmer tilbake til nåverdi. Den kombinerer egenkapitalkostnaden (avkastningen aksjonærene forventer) og gjeldskostnaden etter skatt.</p>',
      '<pre>WACC = (E/V × Re) + (D/V × Rd × (1 - Tc))</pre>',
      '<p>Egenkapitalkostnaden (Re) beregnes som regel med kapitalverdimodellen (CAPM):</p>',
      '<pre>Re = Risikofri rente + Beta × (Markedsavkastning - Risikofri rente)</pre>',
      '<p>Beta måler svingninger. En beta på 1,2 betyr at aksjen svinger 20 % mer enn markedet. Høyere risiko krever høyere forventet avkastning, noe som øker diskonteringsrenten og senker nåverdien.</p>',
      '[AD_ZONE]',
      '<h3>Fri kontantstrøm (FCF)</h3>',
      '<p>Omsetning er forfengelighet, overskudd er fornuft, kontanter er virkelighet. Fri kontantstrøm er kontantene et selskap genererer etter utbetalingene som trengs for å drive virksomheten og vedlikeholde driftsmidlene. Det er pengene som faktisk kan deles ut til aksjonærene.</p>',
      "<p>I kalkulatoren vår fremskriver vi FCF ved å anslå omsetningsvekst og bruke en forventet FCF-margin. Vi legger på en 'sikkerhetsbuffer' som kutter kraftig i disse anslagene - optimisme er verdiinvestorens fiende.</p>",
      '<h3>Terminalverdi</h3>',
      '<p>Siden vi ikke kan fremskrive kontantstrømmer år for år til evig tid, beregner vi en terminalverdi (TV) ved slutten av prognoseperioden (vanligvis år 5). Den representerer verdien av alle kontantstrømmer etter år 5.</p>',
      '<pre>TV = FCF_År5 × (1 + g) / (WACC - g)</pre>',
      "<p>Dette er formelen for evig vekst, der 'g' er den langsiktige vekstraten (som ikke kan være høyere enn BNP-veksten). Alternativt kan man bruke en EBITDA-multippel ved exit, men da blandes relativ markedsprising inn i en ren egenverdiberegning.</p>",
      '<p>Terminalverdien utgjør ofte 60-80 % av den samlede verdsettelsen, og derfor er DCF-modeller svært følsomme for forutsetningene. Bruk dem til å stressteste antakelser, ikke til å finne en absolutt sannhet.</p>',
    ],
  },
  'core-satellite': {
    title: 'Kjerne-satellitt-strategien og 110-regelen for aktivaallokering',
    description:
      'Slik bygger du en portefølje som tåler børskrakk og samtidig kan slå indeksen. Indeksfond i forsvar, aksjeplukking i angrep.',
    body: [
      '<h2>Balansen mellom forsvar og angrep</h2>',
      "<p>Kjerne-satellitt er en måte å bygge en portefølje på som holder kostnader og svingninger nede, samtidig som du får mulighet til å slå markedet. Porteføljen deles i to: en stor, passivt forvaltet 'kjerne' og en mindre, aktivt forvaltet 'satellitt'.</p>",
      '<h3>Kjernen</h3>',
      '<p>Kjernen består typisk av brede indeksfond eller ETF-er (for eksempel S&P 500 eller globale indeksfond). Denne delen sikrer at du får med deg aksjemarkedets risikopremie med minimale kostnader og maksimal spredning.</p>',
      '<h3>Satellitten</h3>',
      '<p>Satellitten inneholder enkeltaksjene du har høyest overbevisning om - de som består Sievoos hovedformel. Fordi kjernen gir stabilitet, kan satellitten være offensiv og konsentrert. Holder du 40 aksjer i satellitten, har du bare laget et dyrt og dårlig konstruert indeksfond. En ekte satellittportefølje bør ikke ha mer enn 5-10 grundig analyserte selskaper.</p>',
      '[AD_ZONE]',
      '<h3>110-regelen</h3>',
      "<p>Aktivaallokeringen forklarer rundt 90 % av variasjonen i porteføljens avkastning. '110-regelen' er en moderne justering av den gamle '100-regelen' for hvor stor aksjeandel du bør ha.</p>",
      '<pre>Aksjeandel = 110 - alder (eller år til mål)</pre>',
      '<p>Vi justerer dette etter tidshorisonten. Er det flere tiår til du trenger pengene, er forsvar (obligasjoner/kontanter) en brems på renters rente. Vi anbefaler:</p>',
      '<ul><li>Over 25 år: 10-20 % forsvar</li><li>10-25 år: 20-50 % forsvar</li><li>Under 10 år: 50-70 % forsvar</li></ul>',
      '<p>Resten av aksjeandelen deles 50/50 mellom kjerne (indekser) og satellitt (enkeltaksjer). Finner du ingen aksjer som består strenge kvalitetskrav, går satellittandelen tilbake til kjernen.</p>',
    ],
  },
  'fire-4pct-rule': {
    title: '4 %-regelen og 25x utgifter: formelen for pensjon og FIRE',
    description:
      'Matematikken bak tidlig pensjon. Trinity-studien, risikoen ved rekkefølgen på avkastningen, og hvordan du regner ut ditt eget FI-tall.',
    body: [
      '<h2>Økonomisk uavhengighet, tidlig pensjon (FIRE)</h2>',
      '<p>Matematikken bak pensjon er overraskende enkel, men ofte misforstått. Målet er ikke å nå en bestemt formue basert på et vilkårlig tall (som én million), men å bygge opp nok kapital til at avkastningen dekker levekostnadene dine på ubestemt tid.</p>',
      '<h3>Trinity-studien</h3>',
      '<p>I 1998 publiserte tre finansprofessorer ved Trinity University en studie som testet ulike uttaksrater over 30-årsperioder med historiske markedsdata. De fant at en portefølje med 50-75 % aksjer tålte et inflasjonsjustert uttak på 4 % med nesten 100 % sannsynlighet, uansett i hvilken rekkefølge avkastningen kom.</p>',
      '<p>Slik oppsto 4 %-regelen. Kan du leve av 4 % av porteføljen, trenger du en portefølje på nøyaktig 25 ganger de årlige utgiftene dine.</p>',
      '<pre>Nødvendig kapital = Årlige utgifter × 25</pre>',
      '[AD_ZONE]',
      '<h3>Risikoen ved avkastningsrekkefølgen</h3>',
      "<p>Den største faren for den som pensjonerer seg tidlig, er rekkefølgen på avkastningen. En gjennomsnittlig avkastning på 7 % over 30 år hjelper lite hvis de tre første årene gir -20 %, -15 % og -10 %. Å ta ut 4 % mens porteføljen samtidig faller, svekker kapitalgrunnlaget varig.</p>",
      "<p>For å motvirke dette bruker mange et 'kontanttelt' eller 'obligasjonstelt' (forsvarsandelen i Sievoos FIRE-kalkulator) - de holder 2-3 års levekostnader i kontanter eller tilsvarende, som de tærer på i nedgangstider, slik at aksjedelen får hente seg inn i fred.</p>",
      '<h3>Matematikken bak renters rente</h3>',
      '<p>Hvor lang tid du trenger til FIRE, bestemmes i praksis bare av sparegraden din i prosent av inntekten. Sparer du 50 % av inntekten, kjøper du ett år med frihet for hvert år du jobber. Med 7 % realavkastning gir en sparegrad på 50 % økonomisk uavhengighet på omtrent 17 år, uansett inntektsnivå.</p>',
    ],
  },
  'moats-rule40': {
    title: 'Vollgraver, 40-regelen og innsidehandel',
    description:
      'Kvalitativ analyse møter kvantitative krav. Hvorfor programvareselskaper prises annerledes, og hvordan du ser at et konkurransefortrinn smuldrer.',
    body: [
      '<h2>Mer enn regnearket</h2>',
      "<p>En DCF-modell er aldri bedre enn forutsetningene. Søppel inn, søppel ut. De kvalitative faktorene - 'kvalitetsportene' i Sievoo - avgjør om kontantstrømprognosene har noe rot i virkeligheten. Et selskap uten vollgrav får marginene spist opp av konkurrenter lenge før år 5.</p>",
      '<h3>Økonomiske vollgraver</h3>',
      '<p>En vollgrav er et strukturelt konkurransefortrinn som beskytter et selskaps lønnsomhet. Det finnes fire hovedtyper:</p>',
      '<ul><li><strong>Nettverkseffekter:</strong> Produktet blir mer verdifullt jo flere som bruker det (f.eks. Visa, Meta).</li><li><strong>Byttekostnader:</strong> Kostnaden (tid, penger, risiko) ved å bytte til en konkurrent er for høy (f.eks. bedriftsprogramvare, bank).</li><li><strong>Kostnadsfortrinn:</strong> Evnen til å produsere billigere enn konkurrentene (f.eks. Amazon, Geico).</li><li><strong>Immaterielle eiendeler:</strong> Merkevarer, patenter eller konsesjoner (f.eks. Apple, legemiddelpatenter).</li></ul>',
      '[AD_ZONE]',
      '<h3>40-regelen</h3>',
      '<p>40-regelen er særlig nyttig for programvareselskaper (SaaS) og selskaper i sterk vekst, og vurderer avveiningen mellom vekst og lønnsomhet. Prinsippet er at omsetningsveksten pluss FCF-marginen til et sunt programvareselskap bør være minst 40 %.</p>',
      '<pre>40-regelen = Omsetningsvekst % + FCF-margin %</pre>',
      '<p>Et selskap som vokser 50 % med -10 % margin består. Et selskap som vokser 20 % med 20 % margin består også. Det er en rask tommelfingerregel for å sikre at veksten ikke kjøpes til en pris som ikke kan vare.</p>',
      "<h3>Skinn i spillet</h3>",
      "<p>Hva ledelsen gjør, sier ofte mer enn hva ledelsen lover. Vi ser etter 'skinn i spillet' - grunnlederstyrte selskaper eller store eierandeler blant innsidere. Enda viktigere er det å følge kjøp i markedet. Som Peter Lynch sa: innsidere kan selge aksjene sine av mange grunner, men de kjøper dem av bare én - de tror kursen skal opp.</p>",
    ],
  },
  'margin-of-safety': {
    title: 'Sikkerhetsmargin: Benjamin Grahams viktigste prinsipp',
    description:
      'Den viktigste ideen i verdiinvestering. Hvorfor kjøp under egenverdi er den eneste reelle beskyttelsen mot å ta feil.',
    body: [
      '<h2>Ideen som får verdiinvestering til å fungere</h2>',
      '<p>Benjamin Graham, som regnes som verdiinvesteringens far, mente at hele disiplinen til en rasjonell investor kan kokes ned til ett begrep: sikkerhetsmargin. Prinsippet er lett å forklare og vanskelig å følge. Betal aldri en pris som ikke gir noen buffer mellom det du betaler og det eiendelen faktisk er verdt.</p>',
      '<p>Alle verdsettelsesmodeller, også DCF-kalkulatoren på Sievoo, er anslag bygget på forutsetninger om fremtiden. Vekst, marginer og diskonteringsrente kan alle bli feil. En sikkerhetsmargin garanterer ikke at du har rett - den sørger for at du overlever å ta feil.</p>',
      '<h3>Pris er det du betaler, verdi er det du får</h3>',
      '<p>Graham skilte skarpt mellom pris og verdi. Prisen settes minutt for minutt av markedets samlede humør. Verdien bestemmes av virksomhetens eiendeler, inntjeningsevne og fremtidige kontantstrømmer. De to kan avvike kraftig og lenge, og det er nettopp det som skaper muligheter for en tålmodig investor.</p>',
      '<p>Å bare kjøpe når prisen ligger godt under ditt anslag for verdien, gir rom for feilanslag, uflaks og uventede konkurransetrusler - ting en DCF-modell per definisjon ikke kan fange fullt ut.</p>',
      '[AD_ZONE]',
      '<h3>Hvor stor margin er nok?</h3>',
      '<p>Graham anga ikke ett fast tall, men foretrakk konsekvent rabatter store nok til å tåle de vanlige humpene i næringslivet. En vanlig tommelfingerregel blant moderne verdiinvestorer er å kreve at egenverdien er minst 20-30 % høyere enn dagens kurs, og mer for mindre eller mindre forutsigbare selskaper.</p>',
      '<pre>Sikkerhetsmargin = (Egenverdi − Pris) / Egenverdi</pre>',
      '<p>På Sievoo er det akkurat dette sikkerhetsbufferen i DCF-kalkulatoren er laget for: den undervurderer bevisst de fremskrevne kontantstrømmene, slik at den beregnede verdien allerede har en innebygd buffer - i stedet for at du må huske å trekke fra noe etterpå.</p>',
      '<h3>Sikkerhetsmargin er ikke spredning</h3>',
      '<p>Det er verdt å skille sikkerhetsmargin fra spredning. Spredning håndterer risikoen for at én enkelt posisjon skader deg hardt; sikkerhetsmargin håndterer risikoen for at analysen din av én posisjon rett og slett er feil. En konsentrert portefølje av selskaper kjøpt med reell sikkerhetsmargin kan være langt mindre risikabel - i Grahams betydning av varig kapitaltap - enn en spredt kurv av overprisede aksjer.</p>',
    ],
  },
  'mr-market': {
    title: 'Mr. Market: Markedet skal tjene deg, ikke lede deg',
    description:
      'Benjamin Grahams berømte lignelse om markedspsykologi. Slik bruker du svingninger som en mulighet i stedet for en kilde til uro.',
    body: [
      '<h2>En lignelse om markedspsykologi</h2>',
      '<p>Benjamin Graham illustrerte markedets følelsesmessige natur med en enkel historie. Tenk deg at du eier en andel i en privat virksomhet sammen med en partner som heter Mr. Market. Hver eneste dag dukker Mr. Market opp på døren din og tilbyr enten å kjøpe andelen din eller å selge deg sin - alltid til en oppgitt pris.</p>',
      '<p>Noen dager er Mr. Market euforisk og nevner en pris langt over hva virksomheten med rimelighet er verdt. Andre dager er han nedtrykt og vil selge sin andel for langt mindre enn den er verdt. Det viktige er at Mr. Market ikke tar det ille opp om du ignorerer ham - har du ingenting å si ham i dag, kommer han bare tilbake i morgen med en ny pris.</p>',
      '<h3>Markedet finnes for å tjene deg</h3>',
      '<p>Grahams poeng var at Mr. Markets daglige humørsvingninger ikke forteller deg noe om hva virksomheten faktisk er verdt. Prisene hans er en mulighet, ikke en ordre. En rasjonell investor står fritt til å handle med ham bare når prisen er god, og overse ham helt resten av tiden.</p>',
      '<p>Dette gir svingninger en ny mening. En fallende aksjekurs i et selskap med uendrede fundamentale forhold er ikke bevis på at du tok feil - det kan rett og slett være Mr. Market som har en dårlig dag, og dermed en invitasjon til å kjøpe mer med bedre sikkerhetsmargin.</p>',
      '[AD_ZONE]',
      '<h3>Når markedets mening faktisk betyr noe</h3>',
      '<p>Å overse Mr. Markets humør betyr ikke å overse markedet helt. Vedvarende kursfall kan av og til gjenspeile reelle forverringer i virksomheten - en voksende konkurranse, en svekket balanse eller et faktisk endret inntjeningsbilde. Disiplinen er å fortsette å sjekke ditt eget, uavhengige anslag for verdien, og oppdatere det når fakta endrer seg - i stedet for å la dagens kurs bli ditt anslag.</p>',
      '<h3>Gjør svingninger til en fordel</h3>',
      '<p>Investorer som tar lignelsen om Mr. Market til seg, ser gjerne på svingninger som en kilde til muligheter heller enn uro. Nedgangstider slutter å være bare en trussel mot formuen og blir et tilbakevendende salg på eierandeler i gode selskaper - forutsatt at verdsettelsen din var solid i utgangspunktet.</p>',
    ],
  },
  'defensive-vs-enterprising': {
    title: 'Den defensive og den driftige investoren: Velg din tilnærming',
    description:
      'Graham delte investorer i to leirer etter tid og temperament. Finn ut hvilken som faktisk passer måten du investerer på.',
    body: [
      '<h2>To ærlige veier til god investering</h2>',
      '<p>Benjamin Graham mente ikke at alle investorer burde analysere enkeltselskaper. Han delte investorer i to legitime kategorier etter hvor mye tid, temperament og innsats de realistisk er villige til å legge inn - og mente at en halvhjertet versjon av den krevende tilnærmingen var den farligste veien av alle.</p>',
      '<h3>Den defensive investoren</h3>',
      '<p>Den defensive investoren prioriterer trygghet og lav innsats fremfor sjansen til ekstraordinær avkastning. Grahams råd til denne gruppen handlet om bred spredning, en fornuftig blanding av aksjer og obligasjoner, og en forkjærlighet for store, solide og veletablerte selskaper fremfor spekulative eller kompliserte situasjoner.</p>',
      '<p>I dag tilsvarer den defensive tilnærmingen i stor grad rimelig indeksinvestering - å eie markedet bredt gjennom fond i stedet for å plukke vinnere. Sievoos kjerne-satellitt-rammeverk bygger dette direkte inn i kjerneandelen.</p>',
      '[AD_ZONE]',
      '<h3>Den driftige investoren</h3>',
      '<p>Den driftige investoren er villig til å bruke reell tid og innsats på analyse i bytte mot muligheten for bedre avkastning enn snittet. Denne veien krever selvstendig analyse av enkeltselskaper, vilje til å gå mot strømmen når tallene tilsier det, og nok emosjonell disiplin til å holde en posisjon gjennom perioder der markedet er uenig med deg.</p>',
      '<p>Graham var tydelig på at denne veien bare lønner seg om den gjøres grundig. En investor som gjør litt analyse, men til syvende og sist følger tips og overskrifter, får verken tryggheten fra den defensive tilnærmingen eller det reelle fortrinnet fra den driftige.</p>',
      '<h3>Velg ærlig</h3>',
      '<p>Det sunneste utgangspunktet er en ærlig vurdering av hvor mye tid du faktisk vil bruke på å lese årsrapporter, følge konkurransebildet og gå gjennom verdsettelsesforutsetningene dine på nytt. Sievoos satellittandel er for investorer som vil gjøre den jobben på noen få selskaper de har stor tro på, mens kjernen er tilgjengelig for alle, uansett hvor mye tid de har til analyse.</p>',
    ],
  },
  'graham-number': {
    title: 'Graham-tallet: En rask sil for undervurderte aksjer',
    description:
      'En enkel formel som kombinerer inntjening og bokført verdi for å finne statistisk billige aksjer, pluss Grahams sjupunkts sjekkliste for defensive investorer.',
    body: [
      '<h2>En rask og konservativ fornuftssjekk</h2>',
      '<p>Lenge før regneark med diskonterte kontantstrømmer ble vanlige, lette Benjamin Graham etter en enkel formel som kombinerte et selskaps inntjeningsevne og balansestyrke i ett konservativt anslag for rimelig verdi. Resultatet, i dag kjent som Graham-tallet, er ikke ment å erstatte en full verdsettelse - det skal peke ut selskaper som fortjener en nærmere titt, og luke ut dem som åpenbart er dyre.</p>',
      '<pre>Graham-tallet = √(22,5 × EPS × Bokført verdi per aksje)</pre>',
      '<p>Konstanten 22,5 kommer fra å multiplisere to av Grahams andre tommelfingerregler for defensive investorer: P/E på høyst 15 og P/B på høyst 1,5 (15 × 1,5 = 22,5). En aksje som handles under Graham-tallet, er etter dette konservative målet statistisk billig både mot inntjeningen og mot nettoverdiene.</p>',
      '<h3>Hvor den fungerer, og hvor den ikke gjør det</h3>',
      '<p>Formelen ble laget for stabile, kapitaltunge og lønnsomme selskaper - typen som preget markedet på Grahams tid. Den er langt mindre nyttig for kapitallette selskaper, selskaper i sterk vekst eller selskaper som går med underskudd, der bokført verdi undervurderer den egentlige verdiskapingen og lav P/E like gjerne kan være et faresignal som et kupp. Bruk den som et første filter for modne, lønnsomme selskaper, ikke som et universelt rangeringsverktøy.</p>',
      '[AD_ZONE]',
      '<h3>Grahams sju kriterier for defensive investorer</h3>',
      '<p>Graham kombinerte Graham-tallet med en bredere sjekkliste for defensive investorer som vurderer enkeltaksjer. I moderne, omtrentlig form er kriteriene:</p>',
      '<ul><li><strong>Tilstrekkelig størrelse:</strong> Et stort, etablert selskap og ikke et mikroselskap.</li><li><strong>Sterk finansiell stilling:</strong> Omløpsmidler minst dobbelt så store som kortsiktig gjeld.</li><li><strong>Stabil inntjening:</strong> Positivt resultat hvert av de siste ti årene.</li><li><strong>Utbyttehistorikk:</strong> Sammenhengende utbytte over lang tid.</li><li><strong>Inntjeningsvekst:</strong> Klar vekst i resultat per aksje det siste tiåret.</li><li><strong>Moderat P/E:</strong> Kurs høyst rundt 15 ganger gjennomsnittlig inntjening.</li><li><strong>Moderat P/B:</strong> Kurs høyst rundt 1,5 ganger bokført verdi, eller P/E × P/B høyst 22,5.</li></ul>',
      '<p>Prøv den interaktive versjonen av både Graham-tallet og sjekklisten i Graham-kalkulatoren, og bruk den sammen med DCF-kalkulatoren heller enn i stedet for den - en aksje som består både en konservativ eiendelsbasert sil og en fremoverskuende kontantstrømmodell, er en langt sterkere kandidat enn en som bare består én av dem.</p>',
    ],
  },
};
